<?php
/**
 * Created by PhpStorm.
 * User: lucian
 * Date: 2/9/2017
 * Time: 2:10 PM
 */

class td_block_rd_1_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_1'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_1_widget");'));

class td_block_rd_2_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_2'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_2_widget");'));

class td_block_rd_3_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_3'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_3_widget");'));

class td_block_rd_4_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_4'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_4_widget");'));

class td_block_rd_5_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_5'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_5_widget");'));

class td_block_rd_6_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_6'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_6_widget");'));

class td_block_rd_7_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_7'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_7_widget");'));

class td_block_rd_8_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_8'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_8_widget");'));

class td_block_rd_9_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_9'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_9_widget");'));

class td_block_rd_10_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_10'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_10_widget");'));

class td_block_rd_11_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_11'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_11_widget");'));

class td_block_rd_12_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_12'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_12_widget");'));

class td_block_rd_13_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_13'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_13_widget");'));

class td_block_rd_14_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_14'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_14_widget");'));

class td_block_rd_15_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_15'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_15_widget");'));

class td_block_rd_16_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_16'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_16_widget");'));

class td_block_rd_17_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_17'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_17_widget");'));

class td_block_rd_18_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_18'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_18_widget");'));

class td_block_rd_19_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_19'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_19_widget");'));

class td_block_rd_20_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_20'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_20_widget");'));

class td_block_rd_21_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_21'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_21_widget");'));

class td_block_rd_22_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_22'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_22_widget");'));

class td_block_rd_23_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_23'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_23_widget");'));

class td_block_rd_24_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_24'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_24_widget");'));

class td_block_rd_25_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_25'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_25_widget");'));

class td_block_rd_26_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_26'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_26_widget");'));

class td_block_rd_27_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_27'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_27_widget");'));

class td_block_rd_28_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_28'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_28_widget");'));

class td_block_rd_29_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_29'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_29_widget");'));

class td_block_rd_30_widget extends td_block_widget {
    var $td_block_id = 'td_block_rd_30'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_rd_30_widget");'));

